application: ebfmxorg
version: pruebas
runtime: go
api_version: go1

#default_expiration: "30d"

handlers:
- url: /css/(.*\.(css))
  static_files: css/\1
  upload: css/(.*\.(css))

- url: /r/css/(.*\.(css))
  static_files: css/\1
  upload: css/(.*\.(css))

- url: /scripts/(.*\.(js))
  static_files: scripts/\1
  upload: scripts/(.*\.(js))

- url: /r/scripts/(.*\.(js))
  static_files: scripts/\1
  upload: scripts/(.*\.(js))

- url: /imgs/(.*\.(gif|png|jpg))
  static_files: imgs/\1
  upload: imgs/(.*\.(gif|png|jpg))
#  expiration: "1h"

- url: /r/imgs/(.*\.(gif|png|jpg))
  static_files: imgs/\1
  upload: imgs/(.*\.(gif|png|jpg))
#  expiration: "1h"

- url: /gfx/(.*\.(gif|png|jpg))
  static_files: gfx/\1
  upload: gfx/(.*\.(gif|png|jpg))
#  expiration: "1h"

- url: /r/gfx/(.*\.(gif|png|jpg))
  static_files: gfx/\1
  upload: gfx/(.*\.(gif|png|jpg))
#  expiration: "1h"

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
#  expiration: "1h"

- url: /app
  mime_type: text/html
  static_files: static/iphone-app.html
  upload: static/iphone-app.html
  expiration: "1h"

- url: /busqueda
  mime_type: text/html
  static_files: static/busqueda-de-ofertas.html
  upload: static/busqueda-de-ofertas.html
#  expiration: "1h"

- url: /favicon.ico
  static_files: imgs/favicon.ico
  upload: imgs/favicon.ico
  expiration: "5d"

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)
#  expiration: "1h"

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|zip))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png|zip))
  expiration: "1h"

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
#  expiration: "1h"

#- url: /(.+)
#  static_files: static/\1/index.html
#  upload: static/(.+)/index.html
#  expiration: "15m"

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html
#  expiration: "1h"

- url: /backend/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
