application: ebfmxorg
version: pruebas
runtime: go
api_version: go1

#default_expiration: "1h"

handlers:
# css
- url: /r/css/(.*\.(css))
  static_files: css/\1
  upload: css/(.*\.(css))

- url: /static/css/(.*\.(css))
  static_files: css/\1
  upload: css/(.*\.(css))

- url: /css/(.*\.(css))
  static_files: css/\1
  upload: css/(.*\.(css))

# scripts
- url: /r/scripts/(.*\.(js))
  static_files: scripts/\1
  upload: scripts/(.*\.(js))

- url: /static/scripts/(.*\.(js))
  static_files: scripts/\1
  upload: scripts/(.*\.(js))

- url: /scripts/(.*\.(js))
  static_files: scripts/\1
  upload: scripts/(.*\.(js))

# imgs
- url: /r/imgs/(.*\.(gif|png|jpg))
  static_files: imgs/\1
  upload: imgs/(.*\.(gif|png|jpg))

- url: /static/imgs/(.*\.(gif|png|jpg))
  static_files: imgs/\1
  upload: imgs/(.*\.(gif|png|jpg))

- url: /imgs/(.*\.(gif|png|jpg))
  static_files: imgs/\1
  upload: imgs/(.*\.(gif|png|jpg))

# gfx
- url: /r/gfx/(.*\.(gif|png|jpg))
  static_files: css/gfx/\1
  upload: css/gfx/(.*\.(gif|png|jpg))

- url: /r/css/gfx/(.*\.(gif|png|jpg))
  static_files: css/gfx/\1
  upload: css/gfx/(.*\.(gif|png|jpg))

- url: /css/gfx/(.*\.(gif|png|jpg))
  static_files: css/gfx/\1
  upload: css/gfx/(.*\.(gif|png|jpg))

- url: /static/css/gfx/(.*\.(gif|png|jpg))
  static_files: css/gfx/\1
  upload: css/gfx/(.*\.(gif|png|jpg))

- url: /gfx/(.*\.(gif|png|jpg))
  static_files: css/gfx/\1
  upload: css/gfx/(.*\.(gif|png|jpg))

# html
- url: /r/(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /app
  mime_type: text/html
  static_files: static/iphone-app.html
  upload: static/iphone-app.html

- url: /busqueda
  mime_type: text/html
  static_files: static/busqueda-de-ofertas.html
  upload: static/busqueda-de-ofertas.html

- url: /favicon.ico
  static_files: imgs/favicon.ico
  upload: imgs/favicon.ico

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|zip|pdf))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png|zip|pdf))

- url: /backend/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
